name: lint-commit

on:
  workflow_call:

jobs:
  lint-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Lint
        uses: wagoid/commitlint-github-action@v3
