name: lint-commit

on:
  workflow_call:

jobs:
  lint-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Debug 1
        run: |
          pwd && ls -al

      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Debug 2
        run: |
          pwd && ls -al

      # - name: Lint
      #   uses: wagoid/commitlint-github-action@v5
      #   with:
      #     configFile: './commitlint.config.js'
