name: lint-commit

on:
  workflow_call:

jobs:
  lint-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Debug
        run: |
          echo "GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH"
          echo "GITHUB_ACTION_REPOSITORY: $GITHUB_ACTION_REPOSITORY"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "GITHUB_PATH: $GITHUB_PATH"
          cat ${{ github.workspace }}/commitlint.config.js

      - name: Lint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: './commitlint.config.js'
