name: lint-commit

on:
  workflow_call:

jobs:
  lint-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Configure
        run: |
          cat > ${{ github.workspace }}/commitlint.config.js << EOF
            module.exports = {
              extends: ["@commitlint/config-conventional"],
              rules:{
                'subject-case': [0, 'never'],
                'scope-case': [2, 'always', ['upper-case', 'lower-case']],
              },
              ignores: [
                (message) => message.includes('WIP'),
                (message) => message.includes('Initial commit'),
              ]
            };
          EOF

      - name: Debug
        run: cat ${{ github.workspace }}/commitlint.config.js

      - name: Lint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: ${{ github.workspace }}/commitlint.config.js
